### Quickstart: Compare runs, choose a model, and deploy it to a REST API

In this quickstart, you will:

- Run a hyperparameter sweep on a training script

- Compare the results of the runs in the MLflow UI

- Choose the best run and register it as a model

- Deploy the model to a REST API

- Build a container image suitable for deployment to a cloud platform


In [4]:
import keras
import numpy as np
import pandas as pd
from hyperopt import STATUS_OK,Trials,fmin,hp,tpe
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import warnings

import mlflow
from mlflow.models import infer_signature

warnings.filterwarnings('ignore')

In [5]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [6]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

import tensorflow as tf
print("Using CPU:", tf.config.list_physical_devices('CPU'))

Using CPU: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [7]:
data = pd.read_csv(
    "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv",
    sep=";",
)
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [8]:
train,test = train_test_split(data,test_size=0.25, random_state=42)
train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
2835            6.3              0.25         0.22            3.30      0.048   
1157            7.8              0.30         0.29           16.85      0.054   
744             7.4              0.38         0.27            7.50      0.041   
1448            7.4              0.16         0.49            1.20      0.055   
3338            7.2              0.27         0.28           15.20      0.046   
...             ...               ...          ...             ...        ...   
4426            6.2              0.21         0.52            6.50      0.047   
466             7.0              0.14         0.32            9.00      0.039   
3092            7.6              0.27         0.52            3.20      0.043   
3772            6.3              0.24         0.29           13.70      0.035   
860             8.1              0.27         0.35            1.70      0.030   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
2835                 41.0                 161.0  0.99256  3.16       0.50   
1157                 23.0                 135.0  0.99980  3.16       0.38   
744                  24.0                 160.0  0.99535  3.17       0.43   
1448                 18.0                 150.0  0.99170  3.23       0.47   
3338                  6.0                  41.0  0.99665  3.17       0.39   
...                   ...                   ...      ...   ...        ...   
4426                 28.0                 123.0  0.99418  3.22       0.49   
466                  54.0                 141.0  0.99560  3.22       0.43   
3092                 28.0                 152.0  0.99129  3.02       0.53   
3772                 53.0                 134.0  0.99567  3.17       0.38   
860                  38.0                 103.0  0.99255  3.22       0.63   

      alcohol  quality  
2835     10.5        6  
1157      9.0        6  
744      10.0        5  
1448     11.2        6  
3338     10.9        6  
...       ...      ...  
4426      9.9        6  
466       9.4        6  
3092     11.4        6  
3772     10.6        6  
860      10.4        8  

[3673 rows x 12 columns]

In [9]:
train[['quality']].values.ravel()

array([6, 6, 5, ..., 6, 6, 8])

In [10]:
train_x = train.drop(['quality'],axis=1).values
train_y = train[['quality']].values.ravel()

test_x = test.drop(['quality'],axis=1).values
test_y = test[['quality']].values.ravel()

train_x,valid_x,train_y,valid_y = train_test_split(train_x,train_y,test_size=0.20, random_state=42)

signature = infer_signature(train_x,train_y)

In [11]:
np.mean(train_x,axis=0)

array([6.86621852e+00, 2.80377808e-01, 3.32597005e-01, 6.42164738e+00,
       4.55513955e-02, 3.53556841e+01, 1.38792376e+02, 9.94074221e-01,
       3.18919333e+00, 4.88396869e-01, 1.05005673e+01])

In [12]:
train_x.shape[1]

11

In [ ]:
mlflow.set_tracking_uri("http://mlflow:5000")

### ANN Model

In [13]:
def train_model(params,epochs,train_x,train_y,valid_x,valid_y,test_x,test_y):

    '''
    - Model architecture
    - Compile the model
    - Train the ANN model with lr and momentum params with MLFLOW tracking
    - Evaluate the model
    - Log the parameters and results
    - log the model
    '''
    mean = np.mean(train_x,axis=0)
    var = np.var(train_x,axis=0)

    model = keras.Sequential(
        [
            keras.Input([train_x.shape[1]]),
            keras.layers.Normalization(mean=mean,variance=var),
            keras.layers.Dense(64,activation='relu'),
            keras.layers.Dense(1)

        ]
    )

    model.compile(optimizer=keras.optimizers.SGD(
        learning_rate=params["lr"],momentum=params["momentum"]
    ),
    loss = "mean_squared_error",
    metrics = [keras.metrics.RootMeanSquaredError()]
    )

    with mlflow.start_run(nested=True):
        model.fit(train_x,train_y,validation_data=(valid_x,valid_y),
                  epochs=epochs,
                  batch_size=64)
        
        eval_result = model.evaluate(valid_x,valid_y,batch_size=64)

        eval_rmse = eval_result[1]

        mlflow.log_params(params)
        mlflow.log_metric("eval_rmse",eval_rmse)


        mlflow.tensorflow.log_model(model,"model",signature=signature)

        return {"loss": eval_rmse, "status": STATUS_OK, "model": model}

In [14]:
def objective(params):
    result = train_model(
        params,
        epochs=3,
        train_x=train_x,
        train_y=train_y,
        valid_x=valid_x,
        valid_y=valid_y,
        test_x=test_x,
        test_y=test_y,
    )
    return result

In [15]:
space = {
    "lr":hp.loguniform("lr",np.log(1e-5),np.log(1e-1)),
    "momentum":hp.uniform("momentum",0.0,1.0)

}

In [27]:
mlflow.set_experiment("wine-quality")
with mlflow.start_run():
    '''
    - Conduct the hyperparameter search using Hyperopt
    - Fetch the details of the best run
    - Log the best parameters, loss, and model
    '''
    mlflow.set_tracking_uri(uri="http://mlflow:5000")
    
    trials = Trials()
    best = fmin(
        fn=objective,
        space=space,
        algo=tpe.suggest,
        max_evals=4,
        trials=trials
    )

    best_run = sorted(trials.results, key=lambda x: x["loss"])[0]

    mlflow.log_params(best)
    mlflow.log_metric("eval_rmse", best_run["loss"])
    mlflow.tensorflow.log_model(best_run["model"], "model", signature=signature)

    print(f"Best parameters: {best}")
    print(f"Best eval rmse: {best_run['loss']}")

2024/11/23 09:06:07 INFO mlflow.tracking.fluent: Experiment with name 'wine-quality' does not exist. Creating a new experiment.


Epoch 1/3                                            

46/46 [==============================] - 0s 2ms/step - loss: 3.2211 - root_mean_squared_error: 1.7947 - val_loss: 0.9209 - val_root_mean_squared_error: 0.9597

Epoch 2/3                                            

46/46 [==============================] - 0s 1ms/step - loss: 0.7388 - root_mean_squared_error: 0.8595 - val_loss: 0.6905 - val_root_mean_squared_error: 0.8309

Epoch 3/3                                            

46/46 [==============================] - 0s 1ms/step - loss: 0.6000 - root_mean_squared_error: 0.7746 - val_loss: 0.5798 - val_root_mean_squared_error: 0.7614

12/12 [==============================] - 0s 842us/step - loss: 0.5798 - root_mean_squared_error: 0.7614

  0%|          | 0/4 [00:00<?, ?trial/s, best loss=?]INFO:tensorflow:Assets written to: /tmp/tmpu68v9qtw/model/data/model/assets


INFO:tensorflow:Assets written to: /tmp/tmpu68v9qtw/model/data/model/assets



🏃 View run unequaled-boar-491 at: http://mlflow:5000/#/experiments/2/runs/774b889135e84300aae016558ce61798

🧪 View experiment at: http://mlflow:5000/#/experiments/2

Epoch 1/3                                                                      

46/46 [==============================] - 0s 2ms/step - loss: 10.7319 - root_mean_squared_error: 3.2760 - val_loss: 2.1893 - val_root_mean_squared_error: 1.4796

Epoch 2/3                                                                      

46/46 [==============================] - 0s 1ms/step - loss: 1.8856 - root_mean_squared_error: 1.3732 - val_loss: 1.6994 - val_root_mean_squared_error: 1.3036

Epoch 3/3                                                                      

46/46 [==============================] - 0s 1ms/step - loss: 1.5313 - root_mean_squared_error: 1.2375 - val_loss: 1.4626 - val_root_mean_squared_error: 1.2094

12/12 [==============================] - 0s 732us/step - loss: 1.4626 - root_mean_squared_error: 1.2094

 25%|

INFO:tensorflow:Assets written to: /tmp/tmp7mxgmy1f/model/data/model/assets



🏃 View run unruly-grouse-287 at: http://mlflow:5000/#/experiments/2/runs/76e8af0016a744529974eb5e8e6d4eb8

🧪 View experiment at: http://mlflow:5000/#/experiments/2                      

Epoch 1/3                                                                      

46/46 [==============================] - 0s 3ms/step - loss: 24.8397 - root_mean_squared_error: 4.9839 - val_loss: 17.2763 - val_root_mean_squared_error: 4.1565

Epoch 2/3                                                                      

46/46 [==============================] - 0s 1ms/step - loss: 12.6515 - root_mean_squared_error: 3.5569 - val_loss: 8.8095 - val_root_mean_squared_error: 2.9681

Epoch 3/3                                                                      

46/46 [==============================] - 0s 1ms/step - loss: 6.6422 - root_mean_squared_error: 2.5772 - val_loss: 4.9570 - val_root_mean_squared_error: 2.2264

12/12 [==============================] - 0s 2ms/step - loss: 4.9570 - root_mean_squared

INFO:tensorflow:Assets written to: /tmp/tmpzrrz15o9/model/data/model/assets



🏃 View run luminous-elk-400 at: http://mlflow:5000/#/experiments/2/runs/899a1b12f493467a982dbc63d159a3a0

🧪 View experiment at: http://mlflow:5000/#/experiments/2                      

Epoch 1/3                                                                      

46/46 [==============================] - 0s 3ms/step - loss: 28.2996 - root_mean_squared_error: 5.3197 - val_loss: 23.5826 - val_root_mean_squared_error: 4.8562

Epoch 2/3                                                                      

46/46 [==============================] - 0s 1ms/step - loss: 17.3860 - root_mean_squared_error: 4.1696 - val_loss: 12.1608 - val_root_mean_squared_error: 3.4872

Epoch 3/3                                                                      

46/46 [==============================] - 0s 1ms/step - loss: 8.1790 - root_mean_squared_error: 2.8599 - val_loss: 5.4740 - val_root_mean_squared_error: 2.3397

12/12 [==============================] - 0s 690us/step - loss: 5.4740 - root_mean_squar

INFO:tensorflow:Assets written to: /tmp/tmp25th68m_/model/data/model/assets



🏃 View run unruly-fawn-90 at: http://mlflow:5000/#/experiments/2/runs/706cd2e7e2154642b7115d6978a46f53

🧪 View experiment at: http://mlflow:5000/#/experiments/2                      

100%|██████████| 4/4 [00:15<00:00,  3.93s/trial, best loss: 0.7614409923553467]
INFO:tensorflow:Assets written to: /tmp/tmp_9pe3eej/model/data/model/assets


INFO:tensorflow:Assets written to: /tmp/tmp_9pe3eej/model/data/model/assets



Best parameters: {'lr': 0.019736677609352368, 'momentum': 0.5713063095086572}
Best eval rmse: 0.7614409923553467
🏃 View run redolent-sow-938 at: http://mlflow:5000/#/experiments/2/runs/c93e8150e9ca45eaadeb5dfee8ed1559
🧪 View experiment at: http://mlflow:5000/#/experiments/2


In [26]:
# mlflow.end_run()

In [28]:
print("MLflow artifact URI:", mlflow.get_artifact_uri())

MLflow artifact URI: /mlflow/artifacts/2/35da88c6407c4b8fad156716072fdd6d/artifacts


### Inferencing


In [29]:
from mlflow.models import validate_serving_input

model_uri = 'runs:/c93e8150e9ca45eaadeb5dfee8ed1559/model'

# The logged model does not contain an input_example.
# Manually generate a serving payload to verify your model prior to deployment.
from mlflow.models import convert_input_example_to_serving_input

# Define INPUT_EXAMPLE via assignment with your own input example to the model
# A valid input example is a data instance suitable for pyfunc prediction
serving_payload = convert_input_example_to_serving_input(test_x)

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

39/39 [==============================] - 0s 547us/step


array([[5.966726 ],
       [6.4063973],
       [6.31239  ],
       ...,
       [6.2349677],
       [6.7018385],
       [5.537076 ]], dtype=float32)

In [31]:
'''
- Load model as a PyFuncModel.
- Predict on a Pandas DataFrame.
'''
model_uri = 'runs:/c93e8150e9ca45eaadeb5dfee8ed1559/model'
loaded_model = mlflow.pyfunc.load_model(model_uri)

import pandas as pd
loaded_model.predict(pd.DataFrame(test_x))

39/39 [==============================] - 0s 733us/step


array([[5.966726 ],
       [6.4063973],
       [6.31239  ],
       ...,
       [6.2349677],
       [6.7018385],
       [5.537076 ]], dtype=float32)

### Register in the model registry

In [32]:
mlflow.register_model(model_uri,"wine-quality")

Successfully registered model 'wine-quality'.
2024/11/23 09:27:49 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: wine-quality, version 1
Created version '1' of model 'wine-quality'.


<ModelVersion: aliases=[], creation_timestamp=1732354069585, current_stage='None', description='', last_updated_timestamp=1732354069585, name='wine-quality', run_id='c93e8150e9ca45eaadeb5dfee8ed1559', run_link='', source='/mlflow/artifacts/2/c93e8150e9ca45eaadeb5dfee8ed1559/artifacts/model', status='READY', status_message='', tags={}, user_id='', version='1'>